### ISSUE TITLE
options-files missing from bundle

### ISSUE THREAD

**Issue by asbjornh** [Arthyon/Unit4Enhancements#15] opened 2017-05-23 08:23 UTC
Occasionally, options.html and options.js are omitted when publishing extension

**Comment by Arthyon** [comment] 2017-05-24 06:48
@asbjornh  Fixed in f2db502?

**Comment by asbjornh** [comment] 2017-05-24 07:39
@Arthyon Hopefully but not necessarily. I can't reproduce the issue anymore

**Comment by Arthyon** [comment] 2017-05-30 10:54
Cannot reproduce anymore. Closing issue

**Closed as completed by Arthyon** 2017-05-30 10:54 UTC
Labels: bug
